name: Build and Push Docker Images

on:
  schedule:
    - cron: "0 20 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      pg_version:
        description: "Optional: Build only this PostgreSQL major version (e.g., 16 or 17). Leave empty to build all versions defined in the matrix."
        required: false
        # No default, empty string '' means build all
        type: string

jobs:
  build-postgres:
    strategy:
      matrix:
        pg_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version != '' && fromJson(format('["{0}"]', github.event.inputs.pg_version)) || fromJson('["16","17"]') }}
    env:
      REGISTRY: ghcr.io
      REPO_NAME: ${{ github.repository }}
      PG_MAJOR_VERSION: ${{ matrix.pg_version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      pg_version: ${{ matrix.pg_version }}
      FULL_IMAGE_TAG: ${{ steps.vars.outputs.FULL_IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get variables
        id: vars
        run: |
          ./get_vars.sh
          echo "FULL_IMAGE_TAG=${FULL_IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Check if image already exists
        id: check_image
        run: |
          TAG_TO_CHECK="${{ steps.vars.outputs.FULL_IMAGE_TAG }}"
          echo "Checking for tag: ${TAG_TO_CHECK}"
          if docker manifest inspect "${TAG_TO_CHECK}" > /dev/null 2>&1; then
            echo "Image ${TAG_TO_CHECK} already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image ${TAG_TO_CHECK} does not exist. Proceeding with build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        if: steps.check_image.outputs.exists == 'false' || (github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version == matrix.pg_version)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BITNAMI_NAME=${{ env.BITNAMI_NAME }}
            PGVECTOR_NAME=${{ env.PGVECTOR_NAME }}
            PG_MAJOR_VERSION=${{ matrix.pg_version }}
          tags: |
            ${{ steps.vars.outputs.FULL_IMAGE_TAG }}
            ${{ matrix.pg_version == '17' && github.event_name != 'pull_request' && format('{0}/{1}:latest', env.REGISTRY, env.REPO_NAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.REPO_NAME }},push-by-digest=false,name-canonical=true,push=${{ github.event_name != 'pull_request' }}