name: Build and Push Docker Images

on:
  schedule:
    - cron: "0 20 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      pg_version:
        description: "Optional: Build only this PostgreSQL major version (e.g., 16 or 17). Leave empty to build all versions defined in the matrix."
        required: false
        # No default, empty string '' means build all
        type: string

jobs:
  build-postgres:
    strategy:
      matrix:
        pg_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version != '' && fromJson(format('["{0}"]', github.event.inputs.pg_version)) || fromJson('["16","17"]') }}
    env:
      REGISTRY: ghcr.io
      REPO_NAME: ${{ github.repository }}
      PG_MAJOR_VERSION: ${{ matrix.pg_version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      pg_version: ${{ matrix.pg_version }}
      FULL_IMAGE_TAG: ${{ steps.vars.outputs.FULL_IMAGE_TAG }}
      image_exists: ${{ steps.check_image.outputs.exists }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get variables
        id: vars
        run: |
          ./get_vars.sh

      - name: Check if image already exists
        id: check_image
        run: |
          TAG_TO_CHECK="${{ steps.vars.outputs.FULL_IMAGE_TAG }}"
          echo "Checking for tag: ${TAG_TO_CHECK}"
          # Try to pull the image first to ensure we have the latest manifest
          if docker pull "${TAG_TO_CHECK}"; then
            echo "Image ${TAG_TO_CHECK} exists in the registry."
            # Optional: Verify with manifest inspect if needed, though pull success implies existence
            docker manifest inspect "${TAG_TO_CHECK}" > /dev/null 2>&1
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Image ${TAG_TO_CHECK} does not exist in the registry or pull failed. Proceeding with build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        if: steps.check_image.outputs.exists == 'false' || (github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version == matrix.pg_version)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BITNAMI_NAME=${{ steps.vars.outputs.BITNAMI_NAME }}
            PGVECTOR_NAME=${{ steps.vars.outputs.PGVECTOR_NAME }}
            PG_MAJOR_VERSION=${{ matrix.pg_version }}
          tags: |
            ${{ steps.vars.outputs.FULL_IMAGE_TAG }}
            ${{ steps.vars.outputs.TAG_SHORT }}
            ${{ steps.vars.outputs.TAG_FULL_PGVECTOR_POSTGRES }}
            ${{ matrix.pg_version == '17' && github.event_name != 'pull_request' && format('{0}/{1}:latest', env.REGISTRY, env.REPO_NAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.REPO_NAME }},push-by-digest=false,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
  test-runner-job:
    needs: build-postgres
    # Run this job only if the corresponding build job built an image
    if: needs.build-postgres.outputs.image_exists == 'false' || (github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version == needs.build-postgres.outputs.pg_version)

    strategy:
      fail-fast: false # Optional: prevent job cancellations if one matrix job fails
      matrix:
        pg_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version != '' && fromJson(format('["{0}"]', github.event.inputs.pg_version)) || fromJson('["16","17"]') }}
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:20-bookworm-slim
      
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image - Dynamically select based on the matrix pg_version
        image: ${{ needs.build-postgres.outputs.FULL_IMAGE_TAG }}
        # Provide the password for postgres
        ports:
          - 5432
        env:
          POSTGRESQL_USERNAME: testuser
          POSTGRESQL_POSTGRES_PASSWORD: rootpassword
          POSTGRESQL_PASSWORD: testpassword
          POSTGRESQL_DATABASE: testdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd "pg_isready -U postgres -h 0.0.0.0 -p 5432"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install test dependencies
        working-directory: ./tests
        run: npm install

      - name: Run User Test
        working-directory: ./tests
        env:
          # Use standard PostgreSQL environment variables for connection within the test script
          PGHOST: postgres
          # Use the dynamically assigned host port
          PGPORT: ${{ job.services.postgres.ports['5432'] }}
          # To use vector extension, we need to use root user
          PGUSER: testuser
          PGPASSWORD: testpassword 
          PGDATABASE: testdb
        run: npm run test 
    
      - name: Run Vector Test
        working-directory: ./tests
        env:
          # Use standard PostgreSQL environment variables for connection within the test script
          PGHOST: postgres
          # Use the dynamically assigned host port
          PGPORT: ${{ job.services.postgres.ports['5432'] }}
          # To use vector extension, we need to use root user
          PGUSER: postgres
          PGPASSWORD: rootpassword 
          PGDATABASE: testdb
        run: npm run test:vector        