on:
  schedule:
    - cron: "0 20 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      pg_version:
        description: "Optional: Build only this PostgreSQL major version (e.g., 16 or 17). Leave empty to build all versions defined in the matrix."
        required: false
        # No default, empty string '' means build all
        type: string

jobs:
  build-postgres:
    strategy:
      matrix:
        pg_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pg_version != '' && fromJson(format('["{0}"]', github.event.inputs.pg_version)) || fromJson('["16","17"]') }}
    env:
      REGISTRY: ghcr.io
      REPO_NAME: ${{ github.repository }}
      PG_MAJOR_VERSION: ${{ matrix.pg_version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get variables
        run: ./get_vars.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BITNAMI_NAME=${{ env.BITNAMI_NAME }}
            PGVECTOR_NAME=${{ env.PGVECTOR_NAME }}
            PG_MAJOR_VERSION=${{ matrix.pg_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:pg${{ matrix.pg_version }}
            ${{ matrix.pg_version == 17 && format('{0}/{1}:latest', env.REGISTRY, env.REPO_NAME) || '' }}
